services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Command\ImportDb\:
    resource: '../src/Command/ImportDb/*'

  App\ImportDb\:
    resource: '../src/ImportDb/*'

  App\ImportDb\Alpha\AlphaImporter:
    arguments:
      - '@filesystem'
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\ImportDb\Alpha\SkippedCard\Collector\SkippedAlphaCardsCollectorInterface'
      - '@App\ImportDb\Alpha\SkippedCard\Converter\SkippedAlphaCardConverterInterface'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\VillageStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\QuestionStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\SeasonStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\KeywordStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\TermStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\InformantStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\CollectorStorage'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\CollectorStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\InformantStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\KeywordStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\TermStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToOne\Persisted\ParagraphStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\Persisted\ProgramStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\Persisted\ProgramStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToOne\Persisted\SubparagraphStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\Formatter\QuestionNumber\Formatter\QuestionNumberFormatterInterface'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\Persisted\ParagraphStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\Persisted\ProgramStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\ParagraphStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\ProgramStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\ProgramStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\SectionStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\QuestionStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\Persisted\ProgramStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\Persisted\ParagraphStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\Persisted\SubparagraphStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\SeasonStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToOne\SectionStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToOne\SubparagraphStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\ParagraphStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\VillageStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\RaionStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\RaionStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\OblastStorage'

  App\ImportDb\Alpha\Storage\ManyToOne\OblastStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\Formatter\QuestionNumber\Parser\QuestionNumberParserInterface'
      - '@monolog.logger.alpha_import'