services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Command\ImportDb\:
    resource: '../src/Command/ImportDb/*'

  App\ImportDb\:
    resource: '../src/ImportDb/*'

  App\ImportDb\Alpha\AlphaImporter:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\VillageStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\QuestionStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToOne\SeasonStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\KeywordStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\TermStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\InformerStorage'
      - '@App\ImportDb\Alpha\Storage\ManyToMany\CollectorStorage'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\CollectorStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\InformerStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\KeywordStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'

  App\ImportDb\Alpha\Storage\ManyToMany\TermStorage:
    arguments:
      - '@Symfony\Bridge\Doctrine\RegistryInterface'
      - '@App\ImportDb\Alpha\ValueTrimmer\AlphaValueConverterInterface'
      - '@monolog.logger.alpha_import'